services:
  - type: web
    name: vpn-telegram-backend
    env: node
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: PORT
        value: 3002
      - key: BOT_TOKEN
        value: 8141794544:AAHH6KKKT_XlxsDQ7lUMAgzkh5o-IBAp8-g
      - key: ADMIN_CHAT_ID
        value: 241316555
      - key: FRONTEND_URL
        value: https://vpn-telegram-l3s9xijgp-vyacheslavs-projects-068c7a87.vercel.app
      - key: OUTLINE_API_URL
        value: https://195.211.124.224:18253
      - key: OUTLINE_API_KEY
        value: 8c7mcGn7P3c_EE9Ct30ETw
      - key: OUTLINE_API_CERT
        value: ./certs/access.txt 